export const DIRECTION_LEFT = 'DIRECTION_LEFT';
export const DIRECTION_RIGHT = 'DIRECTION_RIGHT';

export const STATE_INCOGNITO = 'STATE_INCOGNITO';
export const STATE_RUNNING = 'STATE_RUNNING';
export const STATE_POOPING = 'STATE_POOPING';
